---
# Add workers to existing cluster
- name: Generate join commands
  hosts: k8s_masters[0]
  become: yes
  roles:
    - kubernetes/generate_join_worker

- name: Common system setup for worker nodes
  hosts: k8s_workers:k8s_new_workers
  become: yes
  roles:
    - system-common
    - containerd
    - kubernetes/install-k8s-components

- name: Join worker nodes
  hosts: k8s_workers:k8s_new_workers
  become: yes
  roles:
    - kubernetes/join_worker