---
# ETCD Restore and Cluster Reinit
# Use this playbook for disaster recovery scenarios

- name: Restore ETCD and reinitialize cluster
  hosts: new_cluster
  become: yes
  roles:
    # - system-common
    # - containerd
    # - kubernetes/install-k8s-components
    - etcd/restore