---
- name: Check if node already joined cluster
  stat:
    path: /etc/kubernetes/kubelet.conf
  register: kubelet_conf_check

- name: Join worker to Kubernetes cluster
  command: "{{ worker_join_command }}"
  when: not kubelet_conf_check.stat.exists